zk2_useful_ajax_autocomplete:
    path:  /zk2_ajax_autocomplete
    defaults: { _controller: Zk2UsefulBundle:UsefulForm:entityAjaxAutocomplete }
    
zk2_useful_dependent_entity:
    path:  /zk2_dependent_entity
    defaults: { _controller: Zk2UsefulBundle:UsefulForm:dependentEntity }

zk2_useful_select2_entity:
    path:  /zk2_select2_entity
    defaults: { _controller: Zk2UsefulBundle:UsefulForm:entityAjaxAutocomplete }

zk2_useful_file_ajax_upload:
    path:  /zk2_file_ajax_upload
    defaults: { _controller: Zk2UsefulBundle:UsefulForm:fileAjaxUpload }
    options:
        expose: true
